Repository Git-For-Geeks/Python-projects, pull requests merged in 2022-10, with the labels that each got.

#1 Create testing
  testing
Labels: easy, git-for-geeks

#3 Added Youtube Downloader file
  Youtube Video Downloader/youtube_downloader.py
Labels: git-for-geeks, medium, hacktoberfest

#6 Added image to sketch
  Image to Sketch/Image_to_sketch.py
  Image to Sketch/my.jpeg
Labels: easy, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#8 Added Speed_typing.py
  Speed Typing Test/Speed_typing.py
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#17 Pacman Game
  Pacman Game/Pacman.jpg
  Pacman Game/pacman.py
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#18 Added Digital CLock
  Digital Clock/Digital_clock.py
Labels: easy, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#21 Tic tac toe completed
  Tic Tac Toe/Tictactoe.py
Labels: easy, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#20 Guess The Number
  Guess the Number/ReadME.md
  Guess the Number/code.py
Labels: easy, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#24 GauravMKedia_Calendar_Maker
  Calendar Maker/code.py
Labels: easy, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#27 Python script: VScode snippet maker added
  VScode snippet maker/README.md
  VScode snippet maker/code.txt
  VScode snippet maker/snippet-maker.py
Labels: easy, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#23 Python project : rock_or_mine
  rock_or_mine.py
Labels: easy, hacktoberfest, hacktoberfest-accepted

#28 RockPaperScissor_CodeAdded
  Rock Paper Scissor/RockPaperScissor_by_Sahil/RockPaperScisscor.py
  Rock Paper Scissor/RockPaperScissor_by_Sahil/Selection.jpg
  Rock Paper Scissor/RockPaperScissor_by_Sahil/default.jpeg
  Rock Paper Scissor/RockPaperScissor_by_Sahil/paper.jpeg
  Rock Paper Scissor/RockPaperScissor_by_Sahil/rock.jpeg
  Rock Paper Scissor/RockPaperScissor_by_Sahil/scissor.jpeg
Labels: easy, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#29 ADDED STEGANOGRAPHY PROJECT
  Random Password Generator/password.py
  Steganography/NEW.jpg
  Steganography/NEW_.jpeg
  Steganography/stenodiv.py
Labels: git-for-geeks, hacktoberfest, hacktoberfest-accepted, hard

#32 Weather teller
  Weatherteller.py
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#33 Create: Virtual Painter
  CG-Virtual-Painter/tools.png
  CG-Virtual-Painter/virtual_paint_app.py
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#34 Paint GUI and Digit Recognizer Project using Python added
  Paint GUI and Digit Recognizer/GUI.py
  Paint GUI and Digit Recognizer/img/abc
  Paint GUI and Digit Recognizer/img/img_0.png
  Paint GUI and Digit Recognizer/img/img_0.pngimg_0.png
  Paint GUI and Digit Recognizer/mnist.h5
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#35 SnakeGame
  SnakeGame/SnakeGame.py
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#39 Alarm Clock
  Alarm Clock/AlarmClock.py
  Alarm Clock/bensound-punky.mp3
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#41 file percentage matcher
  File_percentage_matcher/file1.txt
  File_percentage_matcher/file2.txt
  File_percentage_matcher/test.py
Labels: easy, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#43 updated wikipedia random article
  Random Wikipedia Articles/ReadME.md
  Random Wikipedia Articles/main.py
  Random Wikipedia Articles/requirements.txt
Labels: medium, hacktoberfest, hacktoberfest-accepted

#47 <Added cipher code>
  Cipher code/ReadME.md
  Cipher code/cipher.py
Labels: easy, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#48 2048 Game
  2048 Game/2048Game.py
Labels: medium, hacktoberfest, hacktoberfest-accepted

#50 Target practice game
  aimpractice/Target.py
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#51 To-do list
  To-Do List/To_Do_List.py
Labels: medium, hacktoberfest, hacktoberfest-accepted

#52 Added Expense Tracker.py
  Expense Tracker/Expense Tracker.py
Labels: git-for-geeks, hacktoberfest, hacktoberfest-accepted, hard

#55 AQI using Pyhton
  AQI/aqi.py
  AQI/sample_json.json
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#58 python project added
  virtual_painter_computer_graphics/tools.png
  virtual_painter_computer_graphics/virtual_paint_app.py
Labels: git-for-geeks, hacktoberfest, hacktoberfest-accepted, hard

#59 Added Attendance Management System
  Attendance Management System/Attendance.csv
  Attendance Management System/TrainingImages/Aditya Mande.jpg
  Attendance Management System/TrainingImages/Vikramjeet.jpg
  Attendance Management System/atten.py
  Attendance Management System/dlib-19.22.99-cp310-cp310-win_amd64.whl
  Attendance Management System/requirements.txt
  Attendance Management System/test.py
Labels: git-for-geeks, hacktoberfest, hacktoberfest-accepted, hard

#60 Basic Game
  Cipher code/Basic-game.py
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#63 Create handDetection.py
  Hand Detection/handDetection.py
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#64 Plagiarism Detector
  Plagrisim Checker/PlagrisimDetector.py
Labels: easy, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#65 Color deteection using python
  Calci_by_Python/Simple-calculator.py
  Color detection/color_detection.py
  Color detection/colorpic.jpg
  Color detection/colors.csv
  Hangman/Hangman.py
  Password Generator/Password generator.py
  Snake(pygame)/pygame-snake.py
Labels: git-for-geeks, medium, hacktoberfest-accepted

#67 Random Wikipedia Article Generator
  Random Wekipedia Articles/RandomWikipedia.py
Labels: easy, git-for-geeks, hacktoberfest, hacktoberfest-accepted

#66 Added random selector
  Random Selector/rand.py
Labels: hacktoberfest-accepted
